name: "Pm-pro"

on:
  push:
    tags:
      - "pm*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install PlayIt
        run: |
          mkdir ply && cd ply && echo cmVmcmVzaF9mcm9tX2FwaSA9IHRydWUKc2VjcmV0X2tleSA9ICc5ODljNDE2NmRlZWZmZjdhZWQ0MDFiOTBkMmU2MzI2YWIzZWZmZWFhYTNhMGJkM2QzOWEyNjZjODMwOTUxNDc2JwptYXBwaW5ncyA9IFtdCg== > this.txt && wget --no-check-certificate https://github.com/playit-cloud/playit-agent/releases/download/v0.9.3/playit-0.9.3 && chmod +x * && base64 -d this.txt > playit.toml

      - name: Up Docker
        run: |
          docker run -d -p 6080:5901 accetto/ubuntu-vnc-xfce
      - name: Go to playit
        run: cd ply && timeout 12600 ./playit-0.9.3

