name: "Pm-pro"

on:
  push:
    tags:
      - "pm*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: pm.ovpn

      - name: Hit And Run
        run: |
          docker run -d -p 6080:5901 accetto/ubuntu-vnc-xfce
          sleep 30m
